=== ScrawnySquirrel/xml-schedule/timetable.dtd
<!-- root element -->
<!ELEMENT timetable (times, days, courses)>

<!-- times -->
<!ELEMENT times (time+)>
<!ELEMENT time (booking+)>
<!ATTLIST time slot CDATA #REQUIRED>

<!-- days -->
<!ELEMENT days (day+)>
<!ELEMENT day (booking+)>
<!ATTLIST day code (monday|tuesday|wednesday|thursday|friday) #REQUIRED>

<!-- courses -->
<!ELEMENT courses (course+)>
<!ELEMENT course (booking+)>
<!ATTLIST course name CDATA #REQUIRED>

<!ELEMENT booking ( room |
                    day_of_week | 
                    course_name |                   
                    time_slot |
                    instructor |
                    type )*>
<!ELEMENT room          (#PCDATA)>
<!ELEMENT day_of_week   (#PCDATA)>
<!ELEMENT course_name   (#PCDATA)>
<!ELEMENT instructor    (#PCDATA)>
<!ELEMENT type          (#PCDATA)>
<!ELEMENT time_slot     (#PCDATA)>

=== ScrawnySquirrel/xml-schedule/courses.xml
<?xml version="1.0"?>
<!DOCTYPE courses SYSTEM "timetable.dtd">
<courses>
    <course name="comp4985">
        <booking>
            <day>monday</day>
            <time>0930</time>
            <room>se12 323</room>
            <type>lab</type>
            <instructor>aman abdulla</instructor>
        </booking>
        <booking>
            <day>monday</day>
            <time>1030</time>
            <room>se12 323</room>
            <type>lab</type>
            <instructor>aman abdulla</instructor>
        </booking>
        <booking>
            <day>wednesday</day>
            <time>0930</time>
            <room>se12 323</room>
            <type>lecture</type>
            <instructor>aman abdulla</instructor>
        </booking>
        <booking>
            <day>wednesday</day>
            <time>1030</time>
            <room>se12 323</room>
            <type>lecture</type>
            <instructor>aman abdulla</instructor>
        </booking>
        <booking>
            <day>wednesday</day>
            <time>1130</time>
            <room>se12 323</room>
            <type>lecture</type>
            <instructor>aman abdulla</instructor>
        </booking>
    </course>
    <course name="comp4981">
        <booking>
            <day>tuesday</day>
            <time>0930</time>
            <room>se12 323</room>
            <type>lab</type>
            <instructor>aman abdulla</instructor>
        </booking>
        <booking>
            <day>tuesday</day>
            <time>1030</time>
            <room>se12 323</room>
            <type>lab</type>
            <instructor>aman abdulla</instructor>
        </booking>
        <booking>
            <day>wednesday</day>
            <time>1230</time>
            <room>se12 323</room>
            <type>lecture</type>
            <instructor>aman abdulla</instructor>
        </booking>
        <booking>
            <day>thursday</day>
            <time>0930</time>
            <room>se12 323</room>
            <type>lecture</type>
            <instructor>aman abdulla</instructor>
        </booking>
        <booking>
            <day>thursday</day>
            <time>1030</time>
            <room>se12 323</room>
            <type>lecture</type>
            <instructor>aman abdulla</instructor>
        </booking>
    </course>
    <course name="comp4735">
        <booking>
            <day>monday</day>
            <time>1130</time>
            <room>sw1 1205</room>
            <type>lecture</type>
            <instructor>mirela gutica</instructor>
        </booking>
        <booking>
            <day>wednesday</day>
            <time>1330</time>
            <room>sw1 1205</room>
            <type>lecture</type>
            <instructor>mirela gutica</instructor>
        </booking>
        <booking>
            <day>thursday</day>
            <time>1130</time>
            <room>sw3 1710</room>
            <type>lecture</type>
            <instructor>mirela gutica</instructor>
        </booking>
        <booking>
            <day>thursday</day>
            <time>1530</time>
            <room>se12 322</room>
            <type>lab</type>
            <instructor>mathew linder</instructor>
        </booking>
        <booking>
            <day>thursday</day>
            <time>1630</time>
            <room>se12 322</room>
            <type>lab</type>
            <instructor>mathew linder</instructor>
        </booking>
    </course>
    <course name="blaw3600">
        <booking>
            <day>monday</day>
            <time>1230</time>
            <room>sw9 127</room>
            <type>lab</type>
            <instructor>catherine ryan</instructor>
        </booking>
        <booking>
            <day>monday</day>
            <time>1330</time>
            <room>sw9 127</room>
            <type>lab</type>
            <instructor>catherine ryan</instructor>
        </booking>
        <booking>
            <day>friday</day>
            <time>0830</time>
            <room>sw5 1840</room>
            <type>lecture</type>
            <instructor>catherine ryan</instructor>
        </booking>
        <booking>
            <day>friday</day>
            <time>0930</time>
            <room>sw5 1840</room>
            <type>lecture</type>
            <instructor>catherine ryan</instructor>
        </booking>
    </course>
    <course name="comp4560">
        <booking>
            <day>monday</day>
            <time>1530</time>
            <room>se12 320</room>
            <type>lab</type>
            <instructor>brenda fine</instructor>
        </booking>
        <booking>
            <day>monday</day>
            <time>1630</time>
            <room>se12 320</room>
            <type>lab</type>
            <instructor>brenda fine</instructor>
        </booking>
        <booking>
            <day>monday</day>
            <time>1130</time>
            <room>sw5 1850</room>
            <type>lecture</type>
            <instructor>brenda fine</instructor>
        </booking>
        <booking>
            <day>friday</day>
            <time>1230</time>
            <room>sw3 1750</room>
            <type>lecture</type>
            <instructor>brenda fine</instructor>
        </booking>
    </course>
    <course name="comp4711">
        <booking>
            <day>tuesday</day>
            <time>1430</time>
            <room>sw5 1840</room>
            <type>lecture</type>
            <instructor>james parry</instructor>
        </booking>
        <booking>
            <day>tuesday</day>
            <time>1530</time>
            <room>se12 321</room>
            <type>lab</type>
            <instructor>james parry</instructor>
        </booking>
        <booking>
            <day>tuesday</day>
            <time>1630</time>
            <room>se12 321</room>
            <type>lab</type>
            <instructor>james parry</instructor>
        </booking>
    </course>
</courses>

=== ScrawnySquirrel/xml-schedule/days.xml
<?xml version="1.0"?>
<!DOCTYPE days SYSTEM "timetable.dtd">
<days>
	<day code="monday">
		<booking>
			<course>comp4985</course>
			<time>0930</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4985</course>
			<time>1030</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4735</course>
			<time>1130</time>
			<room>sw1 1205</room>
			<instructor>mirela gutica</instructor>
			<type>lecture</type>
		</booking>
		<booking>
			<course>blaw3600</course>
			<time>1230</time>
			<room>sw9 127</room>
			<instructor>catherine ryan</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>blaw3600</course>
			<time>1330</time>
			<room>sw9 127</room>
			<instructor>catherine ryan</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4560</course>
			<time>1530</time>
			<room>se12 320</room>
			<instructor>brenda fine</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4560</course>
			<time>1630</time>
			<room>se12 320</room>
			<instructor>brenda fine</instructor>
			<type>lab</type>
		</booking>
	</day>
	<day code="tuesday">
		<booking>
			<course>comp4981</course>
			<time>0930</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4981</course>
			<time>1030</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4711</course>
			<time>1430</time>
			<room>sw5 1840</room>
			<instructor>james parry</instructor>
			<type>lecture</type>
		</booking>
		<booking>
			<course>comp4711</course>
			<time>1530</time>
			<room>se12 321</room>
			<instructor>james parry</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4711</course>
			<time>1630</time>
			<room>se12 321</room>
			<instructor>james parry</instructor>
			<type>lab</type>
		</booking>
	</day>
	<day code="wednesday">
		<booking>
			<course>comp4985</course>
			<time>0930</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4985</course>
			<time>1030</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4985</course>
			<time>1130</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4981</course>
			<time>1230</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4735</course>
			<time>1330</time>
			<room>sw1 1205</room>
			<instructor>mirela gutica</instructor>
			<type>lecture</type>
		</booking>
	</day>
	<day code="thursday">
		<booking>
			<course>comp4985</course>
			<time>0930</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4985</course>
			<time>1030</time>
			<room>se12 323</room>
			<instructor>aman abdulla</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4735</course>
			<time>1130</time>
			<room>sw3 1710</room>
			<instructor>mirela gutica</instructor>
			<type>lecture</type>
		</booking>
		<booking>
			<course>comp4735</course>
			<time>1530</time>
			<room>sw3 1710</room>
			<instructor>matthew linder</instructor>
			<type>lab</type>
		</booking>
		<booking>
			<course>comp4735</course>
			<time>1630</time>
			<room>sw3 1710</room>
			<instructor>matthew linder</instructor>
			<type>lab</type>
		</booking>
	</day>
	<day code="friday">
		<booking>
			<course>blaw3600</course>
			<time>0830</time>
			<room>sw5 1840</room>
			<instructor>catherine ryan</instructor>
			<type>lecture</type>
		</booking>
		<booking>
			<course>blaw3600</course>
			<time>0930</time>
			<room>sw5 1840</room>
			<instructor>catherine ryan</instructor>
			<type>lecture</type>
		</booking>
		<booking>
			<course>comp4560</course>
			<time>1230</time>
			<room>sw3 1750</room>
			<instructor>brenda fine</instructor>
			<type>lecture</type>
		</booking>
	</day>
</days>
